// Code generated by minifake; DO NOT EDIT.
package example

// FakeJobQueuer implements JobQueuer.
type FakeJobQueuer struct {
	EnqueueStub func(j *Job) error
	DequeueStub func(j *Job) error
	QueueStub   func() []*Job
}

func (fakeImpl *FakeJobQueuer) Enqueue(j *Job) error {
	if fakeImpl.EnqueueStub != nil {
		return fakeImpl.EnqueueStub(j)
	}
	return nil
}
func (fakeImpl *FakeJobQueuer) Dequeue(j *Job) error {
	if fakeImpl.DequeueStub != nil {
		return fakeImpl.DequeueStub(j)
	}
	return nil
}
func (fakeImpl *FakeJobQueuer) Queue() []*Job {
	if fakeImpl.QueueStub != nil {
		return fakeImpl.QueueStub()
	}
	return nil
}

// FakeJobList implements JobList.
type FakeJobList struct {
	AppendStub  func(j *Job) error
	RemoveStub  func(j *Job) error
	GetStub     func(arg0 string) *Job
	RefreshStub func()
}

func (fakeImpl *FakeJobList) Append(j *Job) error {
	if fakeImpl.AppendStub != nil {
		return fakeImpl.AppendStub(j)
	}
	return nil
}
func (fakeImpl *FakeJobList) Remove(j *Job) error {
	if fakeImpl.RemoveStub != nil {
		return fakeImpl.RemoveStub(j)
	}
	return nil
}
func (fakeImpl *FakeJobList) Get(arg0 string) *Job {
	if fakeImpl.GetStub != nil {
		return fakeImpl.GetStub(arg0)
	}
	return nil
}
func (fakeImpl *FakeJobList) Refresh() {
	if fakeImpl.RefreshStub != nil {
		fakeImpl.RefreshStub()
		return
	}
}
