// Code generated by ministub; DO NOT EDIT.
package example

type FakeJobQueuer struct {
	EnqueueStub func(j *Job) error
	DequeueStub func(j *Job) error
	QueueStub   func() []*Job
}

func (f *FakeJobQueuer) Enqueue(j *Job) error {
	return f.EnqueueStub(j)
}
func (f *FakeJobQueuer) Dequeue(j *Job) error {
	return f.DequeueStub(j)
}
func (f *FakeJobQueuer) Queue() []*Job {
	return f.QueueStub()
}
