// Code generated by mimic; DO NOT EDIT.
package test

import "testing"

// FakeBasic implements Basic.
type FakeBasic struct {
	FooStub func() error
	BarStub func(m map[string]string, qux bool)
	AbcStub func(t *testing.T) error
}

var _ Basic = (*FakeBasic)(nil)

func (fakeImpl *FakeBasic) Foo() error {
	if fakeImpl.FooStub != nil {
		return fakeImpl.FooStub()
	}
	return nil
}
func (fakeImpl *FakeBasic) Bar(m map[string]string, qux bool) {
	if fakeImpl.BarStub != nil {
		fakeImpl.BarStub(m, qux)
	}
}
func (fakeImpl *FakeBasic) Abc(t *testing.T) error {
	if fakeImpl.AbcStub != nil {
		return fakeImpl.AbcStub(t)
	}
	return nil
}
