// Code generated by mimic; DO NOT EDIT.
package test

import (
	"image"
	"image/color"
)

// FakeCrossPackageStruct implements CrossPackageStruct.
type FakeCrossPackageStruct struct {
	AtStub         func(x int, y int) color.Color
	BoundsStub     func() image.Rectangle
	ColorModelStub func() color.Model
}

var _ CrossPackageStruct = (*FakeCrossPackageStruct)(nil)

func (fakeImpl *FakeCrossPackageStruct) At(x int, y int) color.Color {
	if fakeImpl.AtStub != nil {
		return fakeImpl.AtStub(x, y)
	}
	return nil
}
func (fakeImpl *FakeCrossPackageStruct) Bounds() image.Rectangle {
	if fakeImpl.BoundsStub != nil {
		return fakeImpl.BoundsStub()
	}
	return image.Rectangle{}
}
func (fakeImpl *FakeCrossPackageStruct) ColorModel() color.Model {
	if fakeImpl.ColorModelStub != nil {
		return fakeImpl.ColorModelStub()
	}
	return nil
}
