// Code generated by mimic; DO NOT EDIT.
package test

// FakeMath implements Math.
type FakeMath[T Number] struct {
	AddStub  func(a T, b T) T
	ZeroStub func() T
}

// Could not generate compile-time interface assertion for FakeMath due to unrecognized constraint "Number" on type parameter T.
func (fakeImpl *FakeMath[T]) Add(a T, b T) T {
	if fakeImpl.AddStub != nil {
		return fakeImpl.AddStub(a, b)
	}
	var zeroT T
	return zeroT
}
func (fakeImpl *FakeMath[T]) Zero() T {
	if fakeImpl.ZeroStub != nil {
		return fakeImpl.ZeroStub()
	}
	var zeroT T
	return zeroT
}
