// Code generated by mimic; DO NOT EDIT.
package test

// FakeConverter implements Converter.
type FakeConverter[From, To any] struct {
	ConvertStub    func(input From) (To, error)
	ConvertAllStub func(inputs []From) ([]To, error)
}

var _ Converter[any, any] = (*FakeConverter[any, any])(nil)

func (fakeImpl *FakeConverter[From, To]) Convert(input From) (To, error) {
	if fakeImpl.ConvertStub != nil {
		return fakeImpl.ConvertStub(input)
	}
	var zeroTo To
	return zeroTo, nil
}
func (fakeImpl *FakeConverter[From, To]) ConvertAll(inputs []From) ([]To, error) {
	if fakeImpl.ConvertAllStub != nil {
		return fakeImpl.ConvertAllStub(inputs)
	}
	return nil, nil
}

// FakeSwapper implements Swapper.
type FakeSwapper[From, To any] struct {
	SwapStub func(a From, b To) (To, From)
	PtrStub  func(input From) *To
}

var _ Swapper[any, any] = (*FakeSwapper[any, any])(nil)

func (fakeImpl *FakeSwapper[From, To]) Swap(a From, b To) (To, From) {
	if fakeImpl.SwapStub != nil {
		return fakeImpl.SwapStub(a, b)
	}
	var zeroTo To
	var zeroFrom From
	return zeroTo, zeroFrom
}
func (fakeImpl *FakeSwapper[From, To]) Ptr(input From) *To {
	if fakeImpl.PtrStub != nil {
		return fakeImpl.PtrStub(input)
	}
	return nil
}
