package mimic

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"path/filepath"
	"slices"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
	"golang.org/x/tools/imports"
)

const stubTemplate = `// Code generated by mimic; DO NOT EDIT.
package {{.PackageName}}

{{- range .Interfaces}}
{{- $interfaceName := .Name}}
{{- $typeParamDecl := .FullTypeParamDecl}}
{{- $typeParamArgs := .TypeParamArgs}}
// Fake{{$interfaceName}} implements {{$interfaceName}}.
type Fake{{$interfaceName}}{{$typeParamDecl}} struct {
{{- range .Methods}}
    {{.MethodName}}Stub func({{.Params}}) {{.Results}}
{{- end}}
}

{{.InterfaceAssertion}}

{{- range .Methods}}
func (fakeImpl *Fake{{$interfaceName}}{{$typeParamArgs}}) {{.MethodName}}({{.Params}}) {{.Results}} {
	if fakeImpl.{{.MethodName}}Stub != nil {
{{- if .HasResults}}
		return fakeImpl.{{.MethodName}}Stub({{.ParamNames}})
{{- else}}
		fakeImpl.{{.MethodName}}Stub({{.ParamNames}})
{{- end}}
	}
{{- if .ZeroDecls}}
	{{.ZeroDecls}}
{{- end}}
{{- if .HasResults}}
	return {{.ZeroResults}}
{{- end}}
}
{{- end}}
{{- end}}
`

type MethodData struct {
	MethodName  string
	Params      string
	Results     string
	HasResults  bool
	ZeroDecls   string
	ZeroResults string
	ParamNames  string
}

type InterfaceData struct {
	Name       string
	Methods    []*MethodData
	TypeParams []*TypeParamData
}

func (i *InterfaceData) FullTypeParamDecl() string {
	if len(i.TypeParams) == 0 {
		return ""
	}
	// Group consecutive type params sharing the same constraint: [From, To any]
	var parts []string
	var names []string
	currentConstraint := i.TypeParams[0].Constraint
	for _, tp := range i.TypeParams {
		if tp.Constraint != currentConstraint {
			parts = append(parts, strings.Join(names, ", ")+" "+currentConstraint)
			names = nil
			currentConstraint = tp.Constraint
		}
		names = append(names, tp.Name)
	}
	parts = append(parts, strings.Join(names, ", ")+" "+currentConstraint)
	return "[" + strings.Join(parts, ", ") + "]"
}

func (i *InterfaceData) TypeParamArgs() string {
	if len(i.TypeParams) == 0 {
		return ""
	}
	var parts []string
	for _, tp := range i.TypeParams {
		parts = append(parts, tp.Name)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

var constraintDefaults = map[string]string{
	"any":        "any",
	"comparable": "int",
}

// InterfaceAssertion returns a compile-time interface assertion, or a comment
// explaining why one could not be generated for unrecognized constraints.
func (i *InterfaceData) InterfaceAssertion() string {
	if len(i.TypeParams) == 0 {
		return fmt.Sprintf("var _ %s = (*Fake%s)(nil)", i.Name, i.Name)
	}
	var concreteTypes []string
	for _, tp := range i.TypeParams {
		concrete, ok := constraintDefaults[tp.Constraint]
		if !ok {
			return fmt.Sprintf("// Could not generate compile-time interface assertion for Fake%s due to unrecognized constraint %q on type parameter %s.", i.Name, tp.Constraint, tp.Name)
		}
		concreteTypes = append(concreteTypes, concrete)
	}
	typeArgs := "[" + strings.Join(concreteTypes, ", ") + "]"
	return fmt.Sprintf("var _ %s%s = (*Fake%s%s)(nil)", i.Name, typeArgs, i.Name, typeArgs)
}

type TypeParamData struct {
	Name       string
	Constraint string
}

// ParseAndStubFromFile is the main entry point for go generated use cases.
func ParseAndStubFromFile(interfaceNames []string, filePath string, formatted bool) ([]byte, error) {
	cfg := &packages.Config{
		Mode: packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedName,
	}

	filePath, err := filepath.Abs(filePath)
	if err != nil {
		return nil, fmt.Errorf("could not resolve absolute path: %w", err)
	}

	pkgs, err := packages.Load(cfg, "file="+filePath)
	if err != nil {
		return nil, fmt.Errorf("could not load package: %w", err)
	}
	if len(pkgs) == 0 {
		return nil, fmt.Errorf("no packages found for %s", filePath)
	}
	pkg := pkgs[0]
	if len(pkg.Errors) > 0 {
		return nil, fmt.Errorf("package errors: %v", pkg.Errors[0])
	}
	var node *ast.File
	for _, f := range pkg.Syntax {
		pos := pkg.Fset.Position(f.Pos())
		if pos.Filename == filePath {
			node = f
			break
		}
	}
	if node == nil {
		return nil, fmt.Errorf("file %s not found in package", filePath)
	}
	return parseAndStub(interfaceNames, node, pkg.TypesInfo, pkg.Types, formatted)

}

// parseAndStub will read from filePath, or directly use src if filePath is empty, to parse
// and generate a stubbed fake implementation of interfaceName. src will not be used if filePath
// is provided.
func parseAndStub(interfaceNames []string, node *ast.File, info *types.Info, pkg *types.Package, formatted bool) ([]byte, error) {
	packageName := node.Name.Name
	allInterfaces := buildInterfaceMap(node)
	var interfaces []*InterfaceData
	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			interfaceType, ok := typeSpec.Type.(*ast.InterfaceType)
			if !ok {
				continue
			}
			interfaceName := typeSpec.Name.Name
			if !slices.Contains(interfaceNames, interfaceName) {
				continue
			}

			typeParams := extractTypeParams(typeSpec.TypeParams)
			var methods []*MethodData
			for _, m := range interfaceType.Methods.List {
				if len(m.Names) == 0 { // Embedded interface
					resolved, err := resolveEmbeddedMethods(m.Type, info, pkg, allInterfaces)
					if err != nil {
						return nil, fmt.Errorf("could not resolve embedded interface in %s: %w", interfaceName, err)
					}
					methods = append(methods, resolved...)
					continue
				}
				// Method
				funcType := m.Type.(*ast.FuncType)
				methods = append(methods, &MethodData{
					MethodName:  m.Names[0].Name,
					Params:      paramsToString(m.Type.(*ast.FuncType).Params),
					Results:     resultsToString(m.Type.(*ast.FuncType).Results),
					ParamNames:  paramNamesToString(m.Type.(*ast.FuncType).Params),
					HasResults:  funcType.Results != nil && len(funcType.Results.List) > 0,
					ZeroDecls:   zeroDeclsToString(info, funcType.Results),
					ZeroResults: zeroResultsToString(info, funcType.Results),
				})
			}
			interfaces = append(interfaces, &InterfaceData{
				Name:       interfaceName,
				Methods:    methods,
				TypeParams: typeParams,
			})
		}
	}

	tmpl, err := template.New("stub").Parse(stubTemplate)
	if err != nil {
		return nil, fmt.Errorf("could not parse stub template: %w", err)
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, struct {
		PackageName string
		Interfaces  []*InterfaceData
	}{
		PackageName: packageName,
		Interfaces:  interfaces,
	})
	if err != nil {
		return nil, fmt.Errorf("could not execute stub template: %w", err)
	}

	bs, err := imports.Process("mimic_tmp_goimports", buf.Bytes(), nil)
	if err != nil {
		return nil, fmt.Errorf("could not call goimports on source: %w", err)
	}

	if formatted {
		formattedCode, err := format.Source(bs)
		if err != nil {
			return nil, fmt.Errorf("failed to format source: %w", err)
		}
		return formattedCode, nil
	}

	return bs, nil
}

func buildInterfaceMap(node *ast.File) map[string]*ast.InterfaceType {
	m := map[string]*ast.InterfaceType{}
	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			iface, ok := ts.Type.(*ast.InterfaceType)
			if !ok {
				continue
			}
			m[ts.Name.Name] = iface
		}
	}
	return m
}

func resolveEmbeddedMethods(expr ast.Expr, info *types.Info, pkg *types.Package, allInterfaces map[string]*ast.InterfaceType) ([]*MethodData, error) {
	// Try local AST resolution first for same-package embeds
	if ident, ok := expr.(*ast.Ident); ok {
		if iface, ok := allInterfaces[ident.Name]; ok {
			return resolveLocalEmbeddedMethods(iface, info, pkg, allInterfaces)
		}
	}

	// Fall back to type info for cross-package embeds
	typ := info.TypeOf(expr)
	if typ == nil {
		return nil, fmt.Errorf("cannot resolve embedded interface: %s", exprToString(expr))
	}
	iface, ok := typ.Underlying().(*types.Interface)
	if !ok {
		return nil, fmt.Errorf("embedded type %s is not an interface", exprToString(expr))
	}
	return methodDataFromTypesInterface(pkg, iface), nil
}

func resolveLocalEmbeddedMethods(iface *ast.InterfaceType, info *types.Info, pkg *types.Package, allInterfaces map[string]*ast.InterfaceType) ([]*MethodData, error) {
	var methods []*MethodData
	for _, field := range iface.Methods.List {
		if len(field.Names) != 0 {
			funcType := field.Type.(*ast.FuncType)
			methods = append(methods, &MethodData{
				MethodName:  field.Names[0].Name,
				Params:      paramsToString(funcType.Params),
				Results:     resultsToString(funcType.Results),
				ParamNames:  paramNamesToString(funcType.Params),
				HasResults:  funcType.Results != nil && len(funcType.Results.List) > 0,
				ZeroDecls:   zeroDeclsToString(info, funcType.Results),
				ZeroResults: zeroResultsToString(info, funcType.Results),
			})
			continue
		}
		nested, err := resolveEmbeddedMethods(field.Type, info, pkg, allInterfaces)
		if err != nil {
			return nil, err
		}
		methods = append(methods, nested...)
	}
	return methods, nil
}

func methodDataFromTypesInterface(pkg *types.Package, iface *types.Interface) []*MethodData {
	var methods []*MethodData
	for i := range iface.NumMethods() {
		method := iface.Method(i)
		sig := method.Type().(*types.Signature)
		methods = append(methods, &MethodData{
			MethodName:  method.Name(),
			Params:      sigParamsToString(pkg, sig),
			Results:     sigResultsToString(pkg, sig),
			ParamNames:  sigParamNamesToString(sig),
			HasResults:  sig.Results().Len() > 0,
			ZeroDecls:   sigZeroDeclsToString(sig),
			ZeroResults: sigZeroResultsToString(pkg, sig),
		})
	}
	return methods
}

func sigParamsToString(pkg *types.Package, sig *types.Signature) string {
	params := sig.Params()
	var parts []string
	for i := range params.Len() {
		p := params.At(i)
		name := p.Name()
		if name == "" {
			name = fmt.Sprintf("arg%d", i)
		}
		qualifier := localQualifier(pkg)
		typeStr := types.TypeString(p.Type(), qualifier)
		if sig.Variadic() && i == params.Len()-1 {
			// Convert []T to ...T for the last param
			slice, ok := p.Type().(*types.Slice)
			if ok {
				typeStr = "..." + types.TypeString(slice.Elem(), qualifier)
			}
		}
		parts = append(parts, name+" "+typeStr)
	}
	return strings.Join(parts, ", ")
}

func sigResultsToString(pkg *types.Package, sig *types.Signature) string {
	results := sig.Results()
	if results.Len() == 0 {
		return ""
	}
	var parts []string
	for i := range results.Len() {
		r := results.At(i)
		qualifier := localQualifier(pkg)
		typeStr := types.TypeString(r.Type(), qualifier)
		if r.Name() != "" {
			parts = append(parts, r.Name()+" "+typeStr)
		} else {
			parts = append(parts, typeStr)
		}
	}
	if len(parts) == 1 {
		return parts[0]
	}
	return fmt.Sprintf("(%s)", strings.Join(parts, ", "))
}

func sigParamNamesToString(sig *types.Signature) string {
	params := sig.Params()
	var names []string
	for i := range params.Len() {
		p := params.At(i)
		name := p.Name()
		if name == "" {
			name = fmt.Sprintf("arg%d", i)
		}
		suffix := ""
		if sig.Variadic() && i == params.Len()-1 {
			suffix = "..."
		}
		names = append(names, name+suffix)
	}
	return strings.Join(names, ",")
}

func sigZeroResultsToString(pkg *types.Package, sig *types.Signature) string {
	results := sig.Results()
	if results.Len() == 0 {
		return ""
	}
	var zeros []string
	for i := range results.Len() {
		zeros = append(zeros, zeroValueForTypesType(pkg, results.At(i).Type()))
	}
	return strings.Join(zeros, ", ")
}

func sigZeroDeclsToString(sig *types.Signature) string {
	results := sig.Results()
	if results.Len() == 0 {
		return ""
	}
	seen := map[string]bool{}
	var decls []string
	for i := range results.Len() {
		tp, ok := results.At(i).Type().(*types.TypeParam)
		if !ok {
			continue
		}
		name := tp.Obj().Name()
		if seen[name] {
			continue
		}
		seen[name] = true
		decls = append(decls, fmt.Sprintf("var zero%s %s", name, name))
	}
	return strings.Join(decls, "\n")
}

func localQualifier(local *types.Package) types.Qualifier {
	return func(pkg *types.Package) string {
		if pkg == local {
			return ""
		}
		return pkg.Name()
	}
}

func zeroValueForTypesType(pkg *types.Package, typ types.Type) string {
	if tp, ok := typ.(*types.TypeParam); ok {
		return "zero" + tp.Obj().Name()
	}
	qualifier := localQualifier(pkg)
	switch t := typ.Underlying().(type) {
	case *types.Basic:
		switch {
		case t.Info()&types.IsBoolean != 0:
			return "false"
		case t.Info()&types.IsNumeric != 0:
			return "0"
		case t.Info()&types.IsString != 0:
			return `""`
		}
	case *types.Pointer, *types.Slice, *types.Map, *types.Interface, *types.Signature, *types.Chan:
		return "nil"
	case *types.Struct:
		return types.TypeString(typ, qualifier) + "{}"
	case *types.Array:
		return types.TypeString(typ, qualifier) + "{}"
	}
	return "nil"
}

func paramsToString(fields *ast.FieldList) string {
	if fields == nil {
		return ""
	}

	var params []string
	for i, field := range fields.List {
		typeString := exprToString(field.Type)
		if len(field.Names) == 0 {
			params = append(params, fmt.Sprintf("arg%d %s", i, typeString))
		} else {
			for _, name := range field.Names {
				params = append(params, name.Name+" "+typeString)
			}
		}
	}

	return strings.Join(params, ", ")
}

func extractTypeParams(fields *ast.FieldList) []*TypeParamData {
	if fields == nil {
		return nil
	}

	var params []*TypeParamData
	for _, field := range fields.List {
		constraint := exprToString(field.Type)
		for _, name := range field.Names {
			params = append(params, &TypeParamData{
				Name:       name.Name,
				Constraint: constraint,
			})
		}
	}

	return params
}

func resultsToString(fields *ast.FieldList) string {
	if fields == nil {
		return ""
	}

	var params []string
	for _, field := range fields.List {
		typeString := exprToString(field.Type)
		if len(field.Names) == 0 {
			params = append(params, typeString)
		} else {
			for _, name := range field.Names {
				params = append(params, name.Name+" "+typeString)
			}
		}
	}
	if len(params) == 1 {
		return params[0]
	}

	return fmt.Sprintf("(%s)", strings.Join(params, ", "))
}

func exprToString(expr ast.Expr) string {
	var sb strings.Builder
	err := format.Node(&sb, token.NewFileSet(), expr)
	if err != nil {
		panic("failed to convert expr to string: " + err.Error())
	}
	return sb.String()
}

func paramNamesToString(fields *ast.FieldList) string {
	if fields == nil {
		return ""
	}

	var names []string
	for i, field := range fields.List {
		callSuffix := ""
		if _, isVariadic := field.Type.(*ast.Ellipsis); isVariadic {
			callSuffix = "..."
		}

		if len(field.Names) == 0 {
			names = append(names, fmt.Sprintf("arg%d%s", i, callSuffix))
			continue
		}
		for _, name := range field.Names {
			names = append(names, name.Name+callSuffix)
		}
	}

	return strings.Join(names, ",")
}

func zeroResultsToString(info *types.Info, results *ast.FieldList) string {
	if results == nil || len(results.List) == 0 {
		return ""
	}

	var zeros []string
	for _, field := range results.List {
		n := len(field.Names)
		if n == 0 {
			n = 1
		}
		z := zeroValueForType(info, field.Type)
		for range n {
			zeros = append(zeros, z)
		}
	}
	return strings.Join(zeros, ", ")
}

func zeroDeclsToString(info *types.Info, results *ast.FieldList) string {
	if results == nil || len(results.List) == 0 {
		return ""
	}

	seen := map[string]bool{}
	var decls []string
	for _, field := range results.List {
		typeInfo := info.TypeOf(field.Type)
		if typeInfo == nil {
			continue
		}
		tp, ok := typeInfo.(*types.TypeParam)
		if !ok {
			continue
		}
		name := tp.Obj().Name()
		if seen[name] {
			continue
		}
		seen[name] = true
		decls = append(decls, fmt.Sprintf("var zero%s %s", name, name))
	}
	return strings.Join(decls, "\n")
}

func zeroValueForType(info *types.Info, expr ast.Expr) string {
	typeInfo := info.TypeOf(expr)
	if typeInfo == nil {
		return zeroValueForExpr(expr)
	}
	if tp, ok := typeInfo.(*types.TypeParam); ok {
		return "zero" + tp.Obj().Name()
	}
	switch t := typeInfo.Underlying().(type) {
	case *types.Basic:
		switch {
		case t.Info()&types.IsBoolean != 0:
			return "false"
		case t.Info()&types.IsNumeric != 0:
			return "0"
		case t.Info()&types.IsString != 0:
			return `""`
		}
	case *types.Pointer, *types.Slice, *types.Map, *types.Interface, *types.Signature, *types.Chan:
		return "nil"
	case *types.Struct:
		return exprToString(expr) + "{}"
	case *types.Array:
		return exprToString(expr) + "{}"
	}
	return "nil"
}

func zeroValueForExpr(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "bool":
			return "false"
		case "string":
			return `""`
		case "error":
			return "nil"
		default:
			// numeric builtins and named types
			if isNumericBuiltin(t.Name) {
				return "0"
			}
			// Special case for newer 'any' keyword instead of interface{}
			if t.Name == "any" {
				return "nil"
			}
			return t.Name + "{}"
		}

	case *ast.SelectorExpr:
		// pkg.Type
		return exprToString(t) + "{}"

	case *ast.StarExpr:
		return "nil"

	case *ast.ArrayType:
		if t.Len == nil {
			return "nil" // slice
		}
		return exprToString(t) + "{}"

	case *ast.StructType:
		return exprToString(t) + "{}"

	case *ast.MapType:
		return "nil"

	case *ast.InterfaceType:
		return "nil"

	case *ast.FuncType:
		return "nil"

	case *ast.ChanType:
		return "nil"

	default:
		return "nil"
	}
}

func isNumericBuiltin(s string) bool {
	switch s {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"byte", "rune",
		"float32", "float64",
		"complex64", "complex128":
		return true
	default:
		return false
	}
}
