package mimic

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestGolden(t *testing.T) {
	entries, err := os.ReadDir("testdata")
	require.NoError(t, err)

	var inputs []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".go") && !strings.HasSuffix(e.Name(), ".golden.go") {
			inputs = append(inputs, e.Name())
		}
	}

	for _, input := range inputs {
		fileName := strings.TrimSuffix(input, ".go")
		t.Run(fileName, func(t *testing.T) {
			t.Parallel()
			inputPath := filepath.Join("testdata", fileName)
			goldenPath := inputPath + "_fake.golden.go"

			src, err := os.ReadFile(inputPath + ".go")
			require.NoError(t, err)

			interfaceNames := extractInterfaceNames(t, string(src))

			got, err := ParseAndStubFromFile(interfaceNames, inputPath+".go", true)
			require.NoError(t, err)

			expected, err := os.ReadFile(goldenPath)
			require.NoError(t, err, "golden file missing: %s", goldenPath)
			require.Equal(t, string(expected), string(got))
		})
	}
}
func TestRegenerateWithStaleFake(t *testing.T) {
	// Simulate the scenario where an interface has changed but the old
	// _fake.go file still exists with a stale interface assertion.
	tmpDir := t.TempDir()

	// Write a source file with an interface
	srcFile := filepath.Join(tmpDir, "svc.go")
	err := os.WriteFile(srcFile, []byte(`package svc

type Service interface {
	Create(name string) error
	Delete(id int) error
}
`), 0644)
	require.NoError(t, err)

	// Write a stale fake that only implements the old version of the interface
	// (missing the Delete method), so the var _ assertion won't type-check.
	staleFake := filepath.Join(tmpDir, "svc_fake.go")
	err = os.WriteFile(staleFake, []byte(`// Code generated by mimic; DO NOT EDIT.
package svc

type FakeService struct {
	CreateStub func(name string) error
}

var _ Service = (*FakeService)(nil)

func (fakeImpl *FakeService) Create(name string) error {
	if fakeImpl.CreateStub != nil {
		return fakeImpl.CreateStub(name)
	}
	return nil
}
`), 0644)
	require.NoError(t, err)

	// Write go.mod so packages.Load can resolve the package
	err = os.WriteFile(filepath.Join(tmpDir, "go.mod"), []byte("module svc\n\ngo 1.23\n"), 0644)
	require.NoError(t, err)

	// Regeneration should succeed despite the stale fake
	got, err := ParseAndStubFromFile([]string{"Service"}, srcFile, true)
	require.NoError(t, err)
	require.Contains(t, string(got), "DeleteStub")
	require.Contains(t, string(got), "CreateStub")
	require.Contains(t, string(got), "var _ Service = (*FakeService)(nil)")
}

func extractInterfaceNames(t *testing.T, src string) []string {
	// Expected format: //go:generate go run github.com/hoenn/mimic ./file.go Name1,Name2
	t.Helper()
	for _, line := range strings.Split(src, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "//go:generate go run github.com/hoenn/mimic") {
			continue
		}
		fields := strings.Fields(line)
		// //go:generate go run github.com/hoenn/mimic ./file.go Name1,Name2
		// fields[0]       [1]  [2]  [3]                          [4]      [5]
		require.GreaterOrEqual(t, len(fields), 6,
			"go:generate directive must include file path and interface names")
		names := strings.Split(fields[5], ",")
		for i := range names {
			names[i] = strings.TrimSpace(names[i])
		}
		return names
	}
	t.Fatal("no //go:generate go run github.com/hoenn/mimic directive found")
	return nil
}
