package mimic

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"strings"
	"text/template"

	"golang.org/x/tools/imports"
)

const stubTemplate = `// Code generated by mimic; DO NOT EDIT.
package {{.PackageName}}

{{- range .Interfaces}}
{{- $interfaceName := .Name}}
// Fake{{$interfaceName}} implements {{$interfaceName}}.
type Fake{{$interfaceName}} struct {
{{- range .Methods}}
    {{.MethodName}}Stub func({{.Params}}) {{.Results}}
{{- end}}
}

{{- range .Methods}}
func (fakeImpl *Fake{{$interfaceName}}) {{.MethodName}}({{.Params}}) {{.Results}} {
	if fakeImpl.{{.MethodName}}Stub != nil {
{{- if .HasResults}}
		return fakeImpl.{{.MethodName}}Stub({{.ParamNames}})
{{- else}}
		fakeImpl.{{.MethodName}}Stub({{.ParamNames}})
{{- end}}
	}
{{- if .HasResults}}
	return {{.ZeroResults}}
{{- end}}
}
{{- end}}
{{- end}}
`

type MethodData struct {
	MethodName  string
	Params      string
	Results     string
	HasResults  bool
	ZeroResults string
	ParamNames  string
}

type InterfaceData struct {
	Name    string
	Methods []*MethodData
}

func ParseAndStubFromSrc(interfaceNames []string, src string, formatted bool) ([]byte, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, "", src, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("could not parse src: %w", err)
	}

	return parseAndStub(interfaceNames, node, formatted)

}

func ParseAndStubFromFile(interfaceNames []string, filepath string, formatted bool) ([]byte, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, filepath, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("could not parse file: %w", err)
	}
	return parseAndStub(interfaceNames, node, formatted)

}

// parseAndStub will read from filepath, or directly use src if filepath is empty, to parse
// and generate a stubbed fake implementation of interfaceName. src will not be used if filepath
// is provided.
func parseAndStub(interfaceNames []string, node *ast.File, formatted bool) ([]byte, error) {
	packageName := node.Name.Name
	allInterfaces := buildInterfaceMap(node)
	var interfaces []*InterfaceData
	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			interfaceType, ok := typeSpec.Type.(*ast.InterfaceType)
			if !ok {
				continue
			}
			interfaceName := typeSpec.Name.Name
			if !contains(interfaceNames, interfaceName) {
				continue
			}
			var methods []*MethodData
			for _, m := range interfaceType.Methods.List {
				if len(m.Names) == 0 { // Embedded interface
					embeddedName, err := embeddedInterfaceName(m.Type)
					if err != nil {
						return nil, fmt.Errorf("could not resolve embedded interface in %s: %w", interfaceName, err)
					}
					resolved, err := resolveEmbeddedMethods(embeddedName, allInterfaces)
					if err != nil {
						return nil, fmt.Errorf("could not resolve embedded interface in %s: %w", interfaceName, err)
					}
					for _, r := range resolved {
						funcType := r.Type.(*ast.FuncType)
						methods = append(methods, &MethodData{
							MethodName:  r.Names[0].Name,
							Params:      paramsToString(funcType.Params),
							Results:     resultsToString(funcType.Results),
							ParamNames:  paramNamesToString(funcType.Params),
							HasResults:  funcType.Results != nil && len(funcType.Results.List) > 0,
							ZeroResults: zeroResultsToString(funcType.Results),
						})
					}
					continue
				}
				// Method
				funcType := m.Type.(*ast.FuncType)
				methods = append(methods, &MethodData{
					MethodName:  m.Names[0].Name,
					Params:      paramsToString(m.Type.(*ast.FuncType).Params),
					Results:     resultsToString(m.Type.(*ast.FuncType).Results),
					ParamNames:  paramNamesToString(m.Type.(*ast.FuncType).Params),
					HasResults:  funcType.Results != nil && len(funcType.Results.List) > 0,
					ZeroResults: zeroResultsToString(funcType.Results),
				})
			}
			interfaces = append(interfaces, &InterfaceData{
				Name:    interfaceName,
				Methods: methods,
			})
		}
	}

	tmpl, err := template.New("stub").Parse(stubTemplate)
	if err != nil {
		return nil, fmt.Errorf("could not parse stub template: %w", err)
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, struct {
		PackageName string
		Interfaces  []*InterfaceData
	}{
		PackageName: packageName,
		Interfaces:  interfaces,
	})
	if err != nil {
		return nil, fmt.Errorf("could not execute stub template: %w", err)
	}

	bs, err := imports.Process("mimic_tmp_goimports", buf.Bytes(), nil)
	if err != nil {
		return nil, fmt.Errorf("could not call goimports on source: %w", err)
	}

	if formatted {
		formattedCode, err := format.Source(bs)
		if err != nil {
			return nil, fmt.Errorf("failed to format source: %w", err)
		}
		return formattedCode, nil
	}

	return bs, nil
}

func buildInterfaceMap(node *ast.File) map[string]*ast.InterfaceType {
	m := map[string]*ast.InterfaceType{}
	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			iface, ok := ts.Type.(*ast.InterfaceType)
			if !ok {
				continue
			}
			m[ts.Name.Name] = iface
		}
	}
	return m
}

func resolveEmbeddedMethods(name string, allInterfaces map[string]*ast.InterfaceType) ([]*ast.Field, error) {
	iface, ok := allInterfaces[name]
	if !ok {
		return nil, fmt.Errorf("cannot resolve cross-package embedded interface: %s", name)
	}
	var methods []*ast.Field
	for _, field := range iface.Methods.List {
		if len(field.Names) != 0 { // Base case, no embedded interface.
			methods = append(methods, field)
			continue
		}
		embeddedName, err := embeddedInterfaceName(field.Type)
		if err != nil {
			return nil, err
		}
		nested, err := resolveEmbeddedMethods(embeddedName, allInterfaces)
		if err != nil {
			return nil, err
		}
		methods = append(methods, nested...)
	}
	return methods, nil
}

func embeddedInterfaceName(expr ast.Expr) (string, error) {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name, nil
	case *ast.SelectorExpr:
		return "", fmt.Errorf("cross-package embed %s not supported", exprToString(expr))
	default:
		return "", fmt.Errorf("unsupported embedded type: %s", exprToString(expr))
	}
}

func contains(slice []string, str string) bool {
	for _, item := range slice {
		if item == str {
			return true
		}
	}
	return false
}

func paramsToString(fields *ast.FieldList) string {
	if fields == nil {
		return ""
	}

	var params []string
	for i, field := range fields.List {
		typeString := exprToString(field.Type)
		if len(field.Names) == 0 {
			params = append(params, fmt.Sprintf("arg%d %s", i, typeString))
		} else {
			for _, name := range field.Names {
				params = append(params, name.Name+" "+typeString)
			}
		}
	}

	return strings.Join(params, ", ")
}

func resultsToString(fields *ast.FieldList) string {
	if fields == nil {
		return ""
	}

	var params []string
	for _, field := range fields.List {
		typeString := exprToString(field.Type)
		if len(field.Names) == 0 {
			params = append(params, typeString)
		} else {
			for _, name := range field.Names {
				params = append(params, name.Name+" "+typeString)
			}
		}
	}
	if len(params) == 1 {
		return params[0]
	}

	return fmt.Sprintf("(%s)", strings.Join(params, ", "))
}

func exprToString(expr ast.Expr) string {
	var sb strings.Builder
	err := format.Node(&sb, token.NewFileSet(), expr)
	if err != nil {
		panic("failed to convert expr to string: " + err.Error())
	}
	return sb.String()
}

func paramNamesToString(fields *ast.FieldList) string {
	if fields == nil {
		return ""
	}

	var names []string
	for i, field := range fields.List {
		callSuffix := ""
		if _, isVariadic := field.Type.(*ast.Ellipsis); isVariadic {
			callSuffix = "..."
		}

		if len(field.Names) == 0 {
			names = append(names, fmt.Sprintf("arg%d%s", i, callSuffix))
			continue
		}
		for _, name := range field.Names {
			names = append(names, name.Name+callSuffix)
		}
	}

	return strings.Join(names, ",")
}

func zeroResultsToString(results *ast.FieldList) string {
	if results == nil || len(results.List) == 0 {
		return ""
	}

	var zeros []string
	for _, field := range results.List {
		n := len(field.Names)
		if n == 0 {
			n = 1
		}
		z := zeroValueForExpr(field.Type)
		for i := 0; i < n; i++ {
			zeros = append(zeros, z)
		}
	}
	return strings.Join(zeros, ", ")
}

func zeroValueForExpr(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "bool":
			return "false"
		case "string":
			return `""`
		case "error":
			return "nil"
		default:
			// numeric builtins and named types
			if isNumericBuiltin(t.Name) {
				return "0"
			}
			// Special case for newer 'any' keyword instead of interface{}
			if t.Name == "any" {
				return "nil"
			}
			return t.Name + "{}"
		}

	case *ast.SelectorExpr:
		// pkg.Type
		return exprToString(t) + "{}"

	case *ast.StarExpr:
		return "nil"

	case *ast.ArrayType:
		if t.Len == nil {
			return "nil" // slice
		}
		return exprToString(t) + "{}"

	case *ast.MapType:
		return "nil"

	case *ast.InterfaceType:
		return "nil"

	case *ast.FuncType:
		return "nil"

	case *ast.ChanType:
		return "nil"

	default:
		return "nil"
	}
}

func isNumericBuiltin(s string) bool {
	switch s {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"byte", "rune",
		"float32", "float64",
		"complex64", "complex128":
		return true
	default:
		return false
	}
}
