name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.22']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Lint
        if: matrix.go-version == '1.22'
        run: make lint

      - name: Build
        run: make build

      - name: Test
        run: make test
